# Wine Dataset Classification using CRISP-DM

## 1. Business Understanding

The goal is to classify wines into one of three different cultivars based on their chemical properties. This type of classification can be useful in the wine industry for quality control, authentication, or identifying the origin of wines. High classification accuracy is the primary success metric.

## 2. Data Understanding

### Load the Dataset and Display Head

In [85]:
import pandas as pd
from sklearn.datasets import load_wine

# Load the Wine dataset
wine = load_wine(as_frame=True)

# Convert to DataFrame
df = (
    wine.frame
    if wine.frame is not None
    else pd.DataFrame(wine.data, columns=wine.feature_names)
)
df["target"] = wine.target

# Display the first few rows
print("--- Dataset Head ---")
df.head()

--- Dataset Head ---

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0

### Display Dataset Information

In [86]:
# Display information about the dataset (data types, non-null counts)
print("--- Dataset Info ---")
df.info()

--- Dataset Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   alcohol                       178 non-null    float64
 1   malic_acid                    178 non-null    float64
 2   ash                           178 non-null    float64
 3   alcalinity_of_ash             178 non-null    float64
 4   magnesium                     178 non-null    float64
 5   total_phenols                 178 non-null    float64
 6   flavanoids                    178 non-null    float64
 7   nonflavanoid_phenols          178 non-null    float64
 8   proanthocyanins               178 non-null    float64
 9   color_intensity               178 non-null    float64
 10  hue                           178 non-null    float64
 11  od280/od315_of_diluted_wines  178 non-null    float64
 12  proline                       178 non-null    float64
 13  target                        178 non-null    int64
dtypes: float64(13), int64(1)
memory usage: 19.6 KB

### Display Target Distribution

In [87]:
# Display the distribution of the target variable
# Note: The target represents the three different cultivars (classes)
print("--- Target Distribution ---")
print(df["target"].value_counts())
print("Target names: ", wine.target_names)

--- Target Distribution ---
target
1    71
0    59
2    48
Name: count, dtype: int64
Target names:  ['class_0' 'class_1' 'class_2']

### Display Dataset Description

In [88]:
# Display basic statistics for numerical features
print("--- Dataset Description ---")
df.describe()

--- Dataset Description ---

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
count,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000
mean,13.000618,2.336348,2.366517,19.494944,99.741573,2.295112,2.029270,0.361854,1.590899,5.058090,0.957449,2.611685,746.893258,0.938202
std,0.811827,1.117146,0.274344,3.339564,14.282484,0.625851,0.998859,0.124453,0.572359,2.318286,0.228572,0.709990,314.907474,0.775035
min,11.030000,0.740000,1.360000,10.600000,70.000000,0.980000,0.340000,0.130000,0.410000,1.280000,0.480000,1.270000,278.000000,0.000000
25%,12.362500,1.602500,2.210000,17.200000,88.000000,1.742500,1.205000,0.270000,1.250000,3.220000,0.782500,1.937500,500.500000,0.000000
50%,13.050000,1.865000,2.360000,19.500000,98.000000,2.355000,2.135000,0.340000,1.555000,4.690000,0.965000,2.780000,673.500000,1.000000
75%,13.677500,3.082500,2.557500,21.500000,107.000000,2.800000,2.875000,0.437500,1.950000,6.200000,1.120000,3.170000,985.000000,2.000000
max,14.830000,5.800000,3.230000,30.000000,162.000000,3.880000,5.080000,0.660000,3.580000,13.000000,1.710000,4.000000,1680.000000,2.000000

## 3. Data Preparation

In [89]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Separate features (X) and target (y)
X = wine.data
y = wine.target

# Split data into training and testing sets (70% train, 30% test)
# Use stratify to ensure the target distribution (cultivar ratio) is similar in train and test sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y
)

# Initialize StandardScaler
scaler = StandardScaler()

# Fit the scaler on the training data and transform both training and testing data
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("--- Data Preparation Complete ---")
print(f"X_train shape: {X_train.shape}, y_train shape: {y_train.shape}")
print(f"X_test shape: {X_test.shape}, y_test shape: {y_test.shape}")
print(
    f"X_train_scaled shape: {X_train_scaled.shape}, X_test_scaled shape: {X_test_scaled.shape}"
)

--- Data Preparation Complete ---
X_train shape: (124, 13), y_train shape: (124,)
X_test shape: (54, 13), y_test shape: (54,)
X_train_scaled shape: (124, 13), X_test_scaled shape: (54, 13)

## 4. Modeling

In [90]:
import joblib
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from xgboost import XGBClassifier

### Model 1: Logistic Regression

In [91]:
# Define hyperparameter grid for Logistic Regression
param_grid_lr = {
    "C": [0.001, 0.01, 0.1, 1, 10, 100],
    "penalty": ["l2"],
    "solver": ["lbfgs", "sag", "saga"],
}

# Initialize GridSearchCV for Logistic Regression
grid_search_lr = GridSearchCV(
    LogisticRegression(random_state=42, max_iter=5000),
    param_grid_lr,
    cv=5,
    scoring="accuracy",
)

# Fit the grid search to the training data
grid_search_lr.fit(X_train_scaled, y_train)

print("--- Logistic Regression Model Training Complete ---")
print("Best parameters for Logistic Regression:", grid_search_lr.best_params_)
print(
    "Best cross-validation accuracy score for Logistic Regression:",
    grid_search_lr.best_score_,
)

# Store the best model
best_lr = grid_search_lr.best_estimator_

--- Logistic Regression Model Training Complete ---
Best parameters for Logistic Regression: {'C': 0.1, 'penalty': 'l2', 'solver': 'lbfgs'}
Best cross-validation accuracy score for Logistic Regression: 0.9836666666666666

### Model 2: Random Forest

In [92]:
# Define hyperparameter grid for Random Forest
param_grid_rf = {
    "n_estimators": [50, 100, 200],
    "max_depth": [None, 5, 10],
    "min_samples_split": [2, 5, 10],
    "criterion": ["gini", "entropy"],
}

# Initialize GridSearchCV for Random Forest
grid_search_rf = GridSearchCV(
    RandomForestClassifier(random_state=42), param_grid_rf, cv=5, scoring="accuracy"
)

# Fit the grid search to the training data
grid_search_rf.fit(X_train, y_train)

print("--- Random Forest Model Training Complete ---")
print("Best parameters for Random Forest:", grid_search_rf.best_params_)
print(
    "Best cross-validation accuracy score for Random Forest:",
    grid_search_rf.best_score_,
)

# Store the best model
best_rf = grid_search_rf.best_estimator_

--- Random Forest Model Training Complete ---
Best parameters for Random Forest: {'criterion': 'gini', 'max_depth': None, 'min_samples_split': 2, 'n_estimators': 200}
Best cross-validation accuracy score for Random Forest: 0.9753333333333334

### Model 3: XGBoost

In [93]:
# Define hyperparameter grid for XGBoost
param_grid_xgb = {
    "n_estimators": [50, 100, 200],
    "max_depth": [3, 5, 7],
    "learning_rate": [0.01, 0.1, 0.3],
    "subsample": [0.8, 1.0],
    "colsample_bytree": [0.8, 1.0],
}

# Initialize GridSearchCV for XGBoost
grid_search_xgb = GridSearchCV(
    XGBClassifier(random_state=42, eval_metric="mlogloss"),
    param_grid_xgb,
    cv=5,
    scoring="accuracy",
)

# Fit the grid search to the training data
grid_search_xgb.fit(X_train_scaled, y_train)

print("--- XGBoost Model Training Complete ---")
print("Best parameters for XGBoost:", grid_search_xgb.best_params_)
print("Best cross-validation accuracy score for XGBoost:", grid_search_xgb.best_score_)

# Store the best model
best_xgb = grid_search_xgb.best_estimator_

--- XGBoost Model Training Complete ---
Best parameters for XGBoost: {'colsample_bytree': 0.8, 'learning_rate': 0.01, 'max_depth': 3, 'n_estimators': 100, 'subsample': 0.8}
Best cross-validation accuracy score for XGBoost: 0.9753333333333334

## 5. Evaluation

In [94]:
from sklearn.metrics import accuracy_score, classification_report

### Evaluate Logistic Regression

In [95]:
# Evaluate Logistic Regression on test set
print("--- Logistic Regression Performance on Test Set ---")
y_pred_lr = best_lr.predict(X_test_scaled)
accuracy_lr = accuracy_score(y_test, y_pred_lr)
print(f"Accuracy: {accuracy_lr:.4f}")

# Use target_names for clear output (cultivar 0, 1, 2)
print(classification_report(y_test, y_pred_lr, target_names=wine.target_names))

--- Logistic Regression Performance on Test Set ---
Accuracy: 1.0000
              precision    recall  f1-score   support

     class_0       1.00      1.00      1.00        18
     class_1       1.00      1.00      1.00        21
     class_2       1.00      1.00      1.00        15

    accuracy                           1.00        54
   macro avg       1.00      1.00      1.00        54
weighted avg       1.00      1.00      1.00        54

### Evaluate Random Forest

In [96]:
# Evaluate Random Forest on test set
print("--- Random Forest Performance on Test Set ---")
y_pred_rf = best_rf.predict(X_test)
accuracy_rf = accuracy_score(y_test, y_pred_rf)
print(f"Accuracy: {accuracy_rf:.4f}")

# Use target_names for clear output (cultivar 0, 1, 2)
print(classification_report(y_test, y_pred_rf, target_names=wine.target_names))

--- Random Forest Performance on Test Set ---
Accuracy: 1.0000
              precision    recall  f1-score   support

     class_0       1.00      1.00      1.00        18
     class_1       1.00      1.00      1.00        21
     class_2       1.00      1.00      1.00        15

    accuracy                           1.00        54
   macro avg       1.00      1.00      1.00        54
weighted avg       1.00      1.00      1.00        54

### Evaluate XGBoost

In [97]:
# Evaluate XGBoost on test set
print("--- XGBoost Performance on Test Set ---")
y_pred_xgb = best_xgb.predict(X_test_scaled)
accuracy_xgb = accuracy_score(y_test, y_pred_xgb)
print(f"Accuracy: {accuracy_xgb:.4f}")

# Use target_names for clear output (cultivar 0, 1, 2)
print(classification_report(y_test, y_pred_xgb, target_names=wine.target_names))

--- XGBoost Performance on Test Set ---
Accuracy: 1.0000
              precision    recall  f1-score   support

     class_0       1.00      1.00      1.00        18
     class_1       1.00      1.00      1.00        21
     class_2       1.00      1.00      1.00        15

    accuracy                           1.00        54
   macro avg       1.00      1.00      1.00        54
weighted avg       1.00      1.00      1.00        54

## Model Comparison

In [98]:
model_performance = {
    "Logistic Regression": accuracy_lr,
    "Random Forest": accuracy_rf,
    "XGBoost": accuracy_xgb,
}

print("--- Model Performance Comparison (Accuracy on Test Set) ---")
for model_name, accuracy in model_performance.items():
    print(f"{model_name}: {accuracy:.4f}")

# Determine the best performing model based on overall accuracy
best_model_name = max(model_performance, key=model_performance.get)
best_test_accuracy = model_performance[best_model_name]

print(
    f"\n--- Best Performing Model (based on Accuracy): {best_model_name} (Accuracy: {best_test_accuracy:.4f}) ---"
)

# Select the actual best model object based on the comparison
if best_model_name == "Logistic Regression":
    final_best_model = best_lr
    requires_scaling = True
elif best_model_name == "Random Forest":
    final_best_model = best_rf
    requires_scaling = False
elif best_model_name == "XGBoost":
    final_best_model = best_xgb
    requires_scaling = True
else:
    # Fallback - should not happen if best_model_name is one of the keys
    final_best_model = best_xgb
    requires_scaling = True

--- Model Performance Comparison (Accuracy on Test Set) ---
Logistic Regression: 1.0000
Random Forest: 1.0000
XGBoost: 1.0000

--- Best Performing Model (based on Accuracy): Logistic Regression (Accuracy: 1.0000) ---

## 6. Deployment

In [99]:
import os

# Define a base directory for saving models for different projects/datasets
base_model_save_dir = os.path.join(os.pardir, "saved_models")

# Define a specific directory for this project's models
project_model_dir = os.path.join(base_model_save_dir, "wine_classification")

# Create the directory if it doesn't exist
os.makedirs(project_model_dir, exist_ok=True)
print(f"Ensured directory exists: {project_model_dir}")


# Define the filenames for the model and scaler within the project directory
model_filename = os.path.join(
    project_model_dir, f"{best_model_name.replace(' ', '_').lower()}_model.joblib"
)
scaler_filename = os.path.join(project_model_dir, "scaler.joblib")

# Save the best performing model
joblib.dump(final_best_model, model_filename)
print(f"Best model ({best_model_name}) saved to: {model_filename}")

# Save the scaler
joblib.dump(scaler, scaler_filename)
print(f"Scaler saved to: {scaler_filename}")


# Save the scaler
config_filename = os.path.join(project_model_dir, "model_config.txt")
with open(config_filename, "w") as f:
    f.write(f"Best_Model: {best_model_name}\n")
    f.write(f"Requires_Scaling: {requires_scaling}\n")
    f.write(f"Target_Names: {wine.target_names.tolist()}\n")
print(f"Model configuration saved to: {config_filename}")

Ensured directory exists: ..\saved_models\wine_classification
Best model (Logistic Regression) saved to: ..\saved_models\wine_classification\logistic_regression_model.joblib
Scaler saved to: ..\saved_models\wine_classification\scaler.joblib
Model configuration saved to: ..\saved_models\wine_classification\model_config.txt